### ISSUE TITLE
[review] use  of alchemical methods in QM

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#100]
Does anyone have a good reference here if we include it?

-In the list of more advanced topics on page 3 the application to QM/MM simulations may be mentioned as well, since this seems to be an area of growing importance

**Comment by mrshirts** [comment]
I agree that free energy calculations for QM/MM should be mentioned as an advanced topic of interest, but should me made clear is out of scope (we should recruit a best practices paper on this!)

**Comment by davidlmobley** [comment]
No, but somewhat relatedly there's the Chodera lab recent work on ANIx endpoint corrections, which gets close to this.

**Comment by jmichel80** [comment]
Could cite some work from Jonathan Essex, Bernard Brooks, Michael Shirts on QM/MM corrections https://pubs.acs.org/doi/abs/10.1021/jp109054j https://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b01188) , highlighting that this is still quite experimental (e.g. https://pubs.acs.org/doi/abs/10.1021/jp506459v) 

Likewise for ML/MM approaches via extended thermodynamic cycles as done by Cole et al. (https://pubs.rsc.org/en/content/articlelanding/2020/FD/D0FD00028K#!divAbstract) and the recent preprint from the Chodera lab @davidlmobley mentioned ; or via direct 'black-box' corrections as in our recent FEP/ML work https://doi.org/10.1021/acs.jcim.0c00600

**Comment by ppxasjsm** [comment]
Sounds good! I can take this bit from here and add a little blurb in the text with the suggested citations.

> (we should recruit a best practices paper on this!)

Looks like you are getting many best practices papers in the future, they seem to lurke everywhere! Now just find willing volunteers.

**Comment by davidlmobley** [comment]
I agree with Julien and don't have anything else to add here.

**Comment by ppxasjsm** [comment]
Great! I'll make the changes for this.

**Comment by ppxasjsm** [comment]
I have added the references.
