### ISSUE TITLE
[review] Forcefield issues

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#101]
Thoughts on this? (@hannahbrucemacdonald )

-Much of the discussion is related to alchemical free-energy calculations in drug design. I think that the success of such calculations is also very dependent on the force field. Although not a topic of the present manuscript, the authors may want to issue a recommendation/warning regarding the validation of automatically generated ligand topologies. I guess, many practitioners just take such topologies for granted.

**Comment by mrshirts** [comment]
I see no reason for not adding that people need to check to make sure the automatically generated ligand topologies 1) are consistent with what the users thinking the are adding, and that 2) the document is focused on getting the correct, reproducible free energy given a choice of force field, but that the choice of force field is a separate question that is very important as well to get answers that are sufficiently close to experiment.

**Comment by davidlmobley** [comment]
Maybe also an explicit warning against web servers that are not associated with a particular reference/well validated practices (without naming ProDRG). I like to tell my students these are like buying off-brand sunglasses from the guy on the street corner.

**Comment by jmichel80** [comment]
Maybe be slightly more explicit here, mention that generic organic forcefields occasionally get torsional energetics badly wrong, users should be mindful of the type of chemistry present in the ligand series they wish to apply AFE methods to.

**Comment by mrshirts** [comment]
Was this text ever added anywhere?

**Comment by ppxasjsm** [comment]
Not that I am aware of so far.

**Comment by mrshirts** [comment]
Added something in 4.1, plus in response to reviewers.

**Comment by ppxasjsm** [comment]
Thank you!
