### ISSUE TITLE
[review] Nomenclature 

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#102]
Thoughts on this?

-In the list of symbols on page 4, the quantity \DeltaG is denoted as Gibbs free energy while \DeltaA is denoted as Helmholtz free energy. However, according to IUPAC or IUPAP these quantities are referred to as Gibbs energy or Helmholtz energy (see https://doi.org/10.1039/9781847557889 or https://doi.org/10.1016/0378-4371(78)90209-1) or sometimes also as “Gibbs function” or “Helmholtz function” or as “free enthalpy” or “free energy” respectively. Of course, the nomenclature used by authors is very common in the field. Therefore, one solution would be to use the IUPAC nomenclature in the List of Symbols along with a footnote explaining that here a different nomenclature is used (or the other way round).

**Comment by mrshirts** [comment]
I'm happy to add some text saying that there are other correct terms for these quantities. I would say, IUPAC can say what they think the name should be, but that hasn't yet changed what 98-99% of the publications/researchers use.  i.e. language is what people use.

**Comment by ppxasjsm** [comment]
That would be great if you could add some text!

**Comment by davidlmobley** [comment]
I agree with @mrshirts suggestion here and it'd be great if he'd edit along those lines. We're using the "dominant" terminology but should clarify that there are other correct terms.

(And yes, it does drive me nuts when people write about the "free enthalpy". )

**Comment by ppxasjsm** [comment]
@mrshirts, I may have too hastily accepted some of the changes. Did you make edits along this way? If not any chance you could address this?

**Comment by ppxasjsm** [comment]
Thanks!
