### ISSUE TITLE
[review] Fonts in figures

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#104]
Use larger fonts in Fig 2 &7, generally try to have equally-sized fonts throughout all Figs.

**Comment by JenkeScheen** [comment]
Presumably for fig 7 the only fonts that need to be made larger are the axis labels for C&D? In fig2 inflating the latex terms should be easy enough. Would you like me to do fig2? I'm not sure how you generated fig 7C/D

**Comment by ppxasjsm** [comment]
There should be a script or notebook in the in the figures directory that has generated C and D. I then used keynote to plug everything together.

**Comment by JenkeScheen** [comment]
for fig7 it should be easiest to just inflate the labels a bit. Am I correct that the keynote file with the assembled figure isn't there in the repo?

**Comment by JenkeScheen** [comment]
Here's a .ai file with larger terms for fig2:
[thermo_cycle_rel_largefont.ai.zip](https://github.com/alchemistry/alchemical-best-practices/files/5298812/thermo_cycle_rel_largefont.ai.zip)

**Comment by JenkeScheen** [comment]
Should probably also make the 'Host' placement on the protein consistent with fig1.

**Comment by ppxasjsm** [comment]
Can you add it as a pull request referecing this issue? sorry for being annoying, but will make things easier for me.

**Comment by ppxasjsm** [comment]
I think this has been address. Thanks you!
