### ISSUE TITLE
[review] Morphing

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#106]
I suppose the issue below is still an open question and has no good answer? Should we give some recommendations here anyway?
 
 What impact does the way of morphing from state A to B have? Rules of thumb what should be avoided, and what helps? I saw sec 7.1.1., but found the focus on dual topology, single topology, or hybrid topology a bit narrow. I do understand that these are the established ones that stood the test of time, but practitioners should also be aware that there is much more out there to choose from, such as enveloping potentials, or variational morphing, which the authors might want to add to their discussion in 7.2.3.

Also @hannahbrucemacdonald

**Comment by mrshirts** [comment]
I'm happy to take a look at this, too.  I think the fundamental concept is that any pathway that transforms A to B is rigorously correct - the difference is the "thermodynamic distance" between them, i.e. a measure. I think the way to approach this is to describe best practices, while pointing out there are other ways to find low thermodynamic distance paths (and give some citations to be of interest).  For example, enveloping distribution sampling has a decently high chance of failure if the system ends up trapped in configurations characteristic of only one endpoint, and it takes a lot of system-dependent finessing to avoid this - if it DOESN'T get trapped, then it's provably the most efficient approach.

**Comment by davidlmobley** [comment]
This is unresolved and mostly unexplored. Could add some text on this. Michael's points are also correct.

**Comment by jmichel80** [comment]
There seems to be variability between codes due to technical decisions about how to implement the morphing (e.g. how to deal with interactions between dummy groups, softcore, how to couple bonded terms etc...) which make production of rules of thumb that apply equally well across packages difficult. Agree  with @davidlmobley that this is not at a stage where best practices have become clear.

**Comment by ppxasjsm** [comment]
If someone would be willing to add a couple of lines along this at an appropriate point that would be great!

**Comment by davidlmobley** [comment]
Added three paragraphs at end of 7.2.3. @mrshirts can you add references please? (And feel free to edit/adjust/etc.) At this point my edits are only in Overleaf.

**Comment by mrshirts** [comment]
OK, added some stuff (in overleaf) and reorganized a bit.

**Comment by mrshirts** [comment]
And talked about it in the response to reviewers paper.
