### ISSUE TITLE
[review] accuracy increase for longer simulations?

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#107]
Is this the case?

Can the authors give some rules of thumb how fast the accuracy increases with simulation length? Is it always as simple as /sqrt(N)?

**Comment by mrshirts** [comment]
It's basically as simple as 1/sqrt(N), where N is the number of uncorrelated samples.  In most cases, the uncertainty of free energy calculations does behave as normally distributed, and thus the 1/sqrt(N) calculation applies. This needs a bit more thought, though, to make it clear why it's the case. As a rule of thumb, this is fine, though.

**Comment by davidlmobley** [comment]
Was this a comment on a particular line number? Could help with edits along these lines.

**Comment by ppxasjsm** [comment]
I would imagine this is referring to section 7.2.5

**Comment by davidlmobley** [comment]
Added this at the end of section 7.2.5 on Overleaf. Please review and close this issue if you're happy with the changes.

**Comment by mrshirts** [comment]
Tweaked a bit more, looks good to me now.

**Comment by ppxasjsm** [comment]
Great thanks! Will take a look in my big sweep.
