### ISSUE TITLE
[review] non-equilibrium methods

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#108]
Should we include more on these?

Non-equilibrium (Crooks) based calculations have been shown to be quite efficient, and IMHO should also be included (I did see it briefly mentioned in 7.2.4).

**Comment by mrshirts** [comment]
I think that although they are useful, they are not yet best practice. I think there are too many things that could go wrong. Maybe we need to recruit a paper on best practice for nonequilibrium calculations.  I think a useful perspective here is that we are writing a list of how to do these calculations for a smart person knows MD but hadn't done them before.  I don't think one would recommend non-equilbrium methods to such a person to start with.   BUT we can say that it is a perfectly valid way to do the calculations, and give some citations. 

The great thing is, we can change our mind in 2 years about whether it should be included!

**Comment by hannahbrucemacdonald** [comment]
> Maybe we need to recruit a paper on best practice for nonequilibrium calculations.


I think this would be a great idea and I would definitely want to read this

**Comment by ppxasjsm** [comment]
>> Maybe we need to recruit a paper on best practice for nonequilibrium calculations.

> I think this would be a great idea and I would definitely want to read this

Seconded!

**Comment by davidlmobley** [comment]
We're close to finishing a big study on, basically, what can go wrong in NEQ calculations and how to detect it. They are not yet at the point, I think, where best practices are definitely known.

I agree they should be mentioned though.

**Comment by ppxasjsm** [comment]
Ok sounds good. Anything I should cite in particular for this? I assume some of the Bert de groot citations etc. I feel like we are already mentioning non-equilirbium methods in the different sampling schemes figure, but happy to expand a little.

**Comment by davidlmobley** [comment]
The work of Vytas Gapsys (De Groot lab) is leading the way here. Cite that, please. Here's also a talk he gave which covers a lot of the work he's done, some of which I believe is still unpublished. Talk has DOI, so citeable: https://zenodo.org/record/3420778

**Comment by davidlmobley** [comment]
Actually here's his other key paper: https://pubs.rsc.org/en/content/articlehtml/2020/sc/c9sc03754c

(He has a Google Scholar profile so that makes this easy.)

**Comment by davidlmobley** [comment]
I'm making some edits to Overleaf:
- Add word "equilibrium" to abstract to indicate that's our focus (which is really the case)
- Added two mentions in Scope (Section 2) that we are NOT covering this here, along with one reference to Gapsys
- Added a mention in 3.2 that specifies we're talking about equilibrium calculations.
- Added sentence at end of 3.2 mentioning these
- Clarify mention of them in 7.2.4

I think that PROBABLY covers it for now. Someone please review and edit further if needed.

**Comment by mrshirts** [comment]
OK, I added a response to reviewers point here.

**Comment by ppxasjsm** [comment]
Looks all good.
