### ISSUE TITLE
Overleaf sync to github no longer works after migration

### ISSUE THREAD

**Issue by davidlmobley** [alchemistry/alchemical-best-practices#110]
After migration, Overleaf synchronization to GitHub seems to no longer work. On overleaf I tried to pull in changes from GitHub but it fails ("not found" error). Same with push.

I don't seem to have an option to reconfigure GItHub synchronization, presumably because this belongs to @ppxasjsm .

**Comment by ppxasjsm** [comment]
Yes...I broke this thinking it could be updated. Will probably have to create a new Overleaf repo, but will do this once all the edits for the revision are in.

**Comment by ppxasjsm** [comment]
I have created a new project, but will still edit the old one while doing the revision. The view link is here:
https://www.overleaf.com/read/pxkprkwxyjkk
