### ISSUE TITLE
[revision] Fig2

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#115]
@JenkeScheen, sorry there is another thing that needs to be fixed and my illustrator isn't working...and don't have time to figure it out right now. 

The $\Delta G_{\mathrm{solvated}}$ label should read:  $\Delta G_{\mathrm{unbound}}$, also make sure if you use LaTeXit, that you use the mathrm for all the labels otherwise the subscripts look funny. Could you please update this?

**Comment by JenkeScheen** [comment]
fixed. sent corrected files to you on slack.

**Comment by ppxasjsm** [comment]
thanks!
