### ISSUE TITLE
Figure 12 has inconsistent labels

### ISSUE THREAD

**Issue by mrshirts** [alchemistry/alchemical-best-practices#119]
The labels on Figure 12 say OA-G6, but it's listed in the text as OA-G3. This should be reconciled!

**Comment by andrrizzi** [comment]
I'm positive the plotted data refers to OA-G6 so the error is in the text. Thanks for catching this.

**Comment by mrshirts** [comment]
So the text will need to be clarified a bit more, since it talks about G3 in two different hosts, which is apparently not the case - one is G3 and one is G6.

**Comment by ppxasjsm** [comment]
Fixed
