### ISSUE TITLE
[review] Inclusion of Gromos

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#98]
Unsurprisingly I think the Gromos community was part of the review and found no Gromos content in the manuscript. I suppose this needs to be rectified. 

I am not sure who knows much about Gromos. I know very little. I can also address some of these points, but if someone is in the know, please let me know. 

Here are some general Gromos content comments:
Section 10: GROMOS is a simulation package with very extensive (alchemical) free energy calculation capabilities and free for academic use. I think it should be mentioned here. (This is for @JenkeScheen really)

And:
1. As a member of the GROMOS development team, I agree with reviewer 1 that GROMOS should be mentioned in the code. I know that GROMOS is not very widely used, but in particular in the field of free energies, it has very broad functionality that is relevant here (see e.g. https://doi.org/10.1021/jp204303a). In fact, the functionalities that GROMOS have had for years are the basis of applications or re-inventions by others. Some examples of functionalities in GROMOS (you do not need to mention all of this in the manuscript, just to demonstrate the relevance of GROMOS for the current work):
- As reviewer 2 points out, the contribution to the free energy of changing a bond-length constraint was already included in GROMOS96 (perturbed SHAKE);
- Use of individual lambda values was described in 2008 (https://doi.org/10.1063/1.2888998), and recently re-invented in the context of smoothstep softcore functions (https://doi.org/10.1021/acs.jctc.0c00237);
- Use of local elevation (or computational flooding) was already implemented in GROMOS96, but reinvented as metadynamics in the early 2000s';
- Use of one-step perturbation (OSP) protocols (https://doi.org/10.1021/jp9605212), now marketed as a commercial software by SILCSbio (https://silcsbio.com/our-software/);
- Use of enveloping distribution sampling (https://doi.org/10.1063/1.2730508) and its accelerated variant (https://doi.org/10.1021/acs.jpcb.8b02725), hinted at by reviewer 3;
- Use of extended TI (https://doi.org/10.1021/acs.jctc.6b00458).

Similarly, for setup and analysis, you may want to mention the gromos++ suite of programs (https://doi.org/10.1021/ct2003622), which contains the standard tools to perform (extended) TI, OSP, BAR, and (obviously) to set up GROMOS simulations. Of relevance to the wider community is a tool to perform post-MD corrections to charge-changing calculations, which is readily used on configurations generated by other MD engines, as outlined in reference 143. 
2. The previous comment brings me to a remark you make at the end of section 7.2.2 that there is currently no work available systematically comparing charge-change corrections and other approaches. We have ourselves just submitted a revision of a manuscript to JCTC that addresses just this issue. I will send you a preprint by direct mail. I have good hopes that our work will come out soon.

**Comment by davidlmobley** [comment]
I don't. But... we could ask Chris Oostenbrink if he wants to propose some concrete edits (I don't know if the reviewer is him, but he's one of our editors). The citations are all good and things we should cite though.

Also the paper they note sounds like it'd be helpful and worth citing. A comparison of charge changes has indeed been a gap in this area. If you want to send it to me when you have it, I can add some discussion of this and a reference.

**Comment by ppxasjsm** [comment]
I am happy to ask if Chris would like to propose some edits. This might be the easiest really.

**Comment by dfhahn** [comment]
Chris is certainly the better contributor here, but if he can't, I might be able to help.

**Comment by ppxasjsm** [comment]
Oh that would be great! I haven't followed up on this yet, will email you both.
