### ISSUE TITLE
[review] Dealing with charges and changes in constraint length

### ISSUE THREAD

**Issue by ppxasjsm** [alchemistry/alchemical-best-practices#99]
Any thoughts on this one?

-At the end of section 7.1.1 on pages 15/16 the following statement appears: “Typical molecular dynamics engines are not set up to recognize this change, or at least not to correctly include contributions to the free energy from changing constraints/constraint length, so results for a transformation would usually be erroneous.”
This statement is a bit surprising since methods to calculate the contribution of the work done by constraint forces have been described a few times, e.g.:
	-Van Gunsteren, W.F., In van Gunsteren W.F. and Weiner, P.K. (Eds.) Computer Simulation of Biomolecular Systems: Theoretical and Experimental Applications, ESCOM, Leiden, 1989, pp. 1-26.
	-Pearlman, D.A., Kollman, P.A., The overlooked bond-stretching contribution in free energy perturbation calculations, J. Chem. Phys. 1991, 94(6), 4532-4545.
	-Straatsma, T.P., Zacharias, M., McCammon, J.A., Holonomic constraint contribution to free energy differences from thermodynamic integration molecular dynamics simulations, Chem. Phys. Lett., 1992, 196(3-4), 297-302.
	-Pearlman, D.A., Determining the contributions of constraints in free energy calculations: Development, characterization, and recommendations, J. Chem. Phys. 1993, 98(11), 8964-8957.
One implementation, based on integrating over the constraint forces, can for example be found in the MD code GROMOS. I suggest to mention the availability of both the theory and also practical implementations in the manuscript.
-In section 7.2.2, when discussing changes in net charge the “Double-system/single-box” setup described by Gapsys et al. may be mentioned. It is related to the alchemical ion approach but can be mentioned here for completeness and to help newcomers to the field in sorting the various approaches.
Gapsys, V., Michielssens, S., Peters, J. H., DeGroot, B. L., Leonov, H. Calculation of Binding Free Energies, In Andreas Kukol (ed.), Molecular Modeling of Proteins, Methods in Molecular Biology, vol. 1215, doi: 10.1007/978-1-4939-1465-4_9, Springer Science+Business Media New York 2015.

Also this:
I agree with the notes in 7.2.2. that no agreed upon way to handle changes in total charges is available. The authors might consider adding (if they agree) that whenever there is a change of total charge, direct comparison to experiment is meaningless, because in experiments the total charge is always conserved (otherwise the test tube would explode). One might even go so far as to say that any calculation with change in total charge is meaningless…which kind of solves the problem from an unexpected angle.

**Comment by davidlmobley** [comment]
I'd add the references/make the suggested changes. 

I also agree with the point on section 7.2.2; this is one reason why doing hydration free energies for ions is a bad idea.

**Comment by davidlmobley** [comment]
(Note though that this point does not exactly apply to binding, when one is transferring the ligand from the binding site to solution, so there doesn't have to be a change in formal charge.)

**Comment by jmichel80** [comment]
Add the recent body of work of Oostenbrink and co-workers on charge corrections in binding free energy calculations. I don't think any of the charge correction approaches have been sufficiently tested  in depth to establish a best practice

**Comment by davidlmobley** [comment]
@mrshirts should comment on the constraint issue, as he dealt with this iN GROMACS at one point/investigated it. He may be in a better position to write something on that.

**Comment by davidlmobley** [comment]
Pinged Shirts on Slack.

**Comment by mrshirts** [comment]
I added some comments on section 7.1 on this.  GROMACS supports the constraint changes in TI, but not in potential energy differences (so not BAR or MBAR).  I qualified what does and doesn't support it, and told people to look at their user manuals to check.

**Comment by ppxasjsm** [comment]
Thanks you, I also added a couple more of the suggested references.
